# Generated by Django 3.2.3 on 2021-05-14 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_deleted', models.DateTimeField(auto_now=True, verbose_name='Дата удаления')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('photo_location', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участки',
            },
        ),
        migrations.CreateModel(
            name='ModelsHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_deleted', models.DateTimeField(auto_now=True, verbose_name='Дата удаления')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('hierarchy_number', models.PositiveIntegerField(blank=True, verbose_name='Номер иерархии')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workshops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_deleted', models.DateTimeField(auto_now=True, verbose_name='Дата удаления')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('photo_location', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('Hierarchy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionaries_output.modelshierarchy', verbose_name='Номер иерархии')),
            ],
            options={
                'verbose_name': 'Цех',
                'verbose_name_plural': 'Цеха',
            },
        ),
        migrations.CreateModel(
            name='Productions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_deleted', models.DateTimeField(auto_now=True, verbose_name='Дата удаления')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('photo_location', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('Hierarchy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionaries_output.modelshierarchy', verbose_name='Номер иерархии')),
            ],
            options={
                'verbose_name': 'Производство',
                'verbose_name_plural': 'Производства',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_deleted', models.DateTimeField(auto_now=True, verbose_name='Дата удаления')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('photo_location', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('compartment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionaries_output.compartments', verbose_name='Участок')),
                ('production_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Productions', to='dictionaries_output.productions', verbose_name='Производство')),
                ('workshop_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionaries_output.workshops', verbose_name='Цех')),
            ],
            options={
                'verbose_name': 'Местоположение оборудования',
                'verbose_name_plural': 'Местоположения оборудования',
            },
        ),
        migrations.AddField(
            model_name='compartments',
            name='Hierarchy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionaries_output.modelshierarchy', verbose_name='Номер иерархии'),
        ),
    ]
