# Generated by Django 3.2.3 on 2021-05-14 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries_output', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelshierarchy',
            options={'verbose_name': 'Номер иерархии', 'verbose_name_plural': 'Номера иерархии'},
        ),
        migrations.RenameField(
            model_name='compartments',
            old_name='Hierarchy',
            new_name='hierarchy',
        ),
        migrations.RenameField(
            model_name='productions',
            old_name='Hierarchy',
            new_name='hierarchy',
        ),
        migrations.RenameField(
            model_name='workshops',
            old_name='Hierarchy',
            new_name='hierarchy',
        ),
    ]
